{
  "uid" : "31e308fd6338358a",
  "name" : "test_deposit_card_success",
  "fullName" : "deposit_test#test_deposit_card_success",
  "historyId" : "c3e050417621e89583b9b23474823c36",
  "time" : {
    "start" : 1593598011530,
    "stop" : 1593598014104,
    "duration" : 2574
  },
  "status" : "broken",
  "statusMessage" : "ValueError: Receivable's account incorrect with 123456789",
  "statusTrace" : "username = 'jackson', pwd = 'a111222', amount = 50, service_type = ['DirectPay', 'WeiXin', 'Alipay']\n\n    @allure.feature('Positive')\n    @allure.story('story')\n    @allure.step('step')\n    @pytest.mark.run(order=7)\n    # 可以用XPATH補一下應收帳款response的號碼\n    def test_deposit_card_success(username='jackson', pwd='a111222', amount=50, service_type=None):\n        # DirectPay(卡對卡), WeiXin(微信轉卡), Alipay(支付寶轉卡)\n    \n        count = 0\n        error = 0\n    \n        b.login(username, pwd)\n        if service_type is None:\n            service_type = ['DirectPay', 'WeiXin', 'Alipay']\n    \n        for typ in service_type:\n            cards = b.deposit(amount, typ)\n            if '123456789' in cards['text']:\n                lis = [\n                    cards['status_code'] == 200,\n                    '50' in cards['text'],\n                    '123456789' in cards['text']\n                       ]\n    \n                for judge in lis:\n                    count += 1\n                    if not judge:\n                        error += 1\n                        logging.debug('\\tlis的第%s行錯誤' % count)\n    \n                if error >= 1:\n                    raise AssertionError(\n                        \"\\tError count : %s\\n%s\" % (error, time.strftime('%Y-%m-%d %H:%M:%S')))\n            else:\n>               raise ValueError(\"Receivable's account incorrect with 123456789\")\nE               ValueError: Receivable's account incorrect with 123456789\n\ndeposit_test.py:97: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "ValueError: Receivable's account incorrect with 123456789",
    "statusTrace" : "username = 'jackson', pwd = 'a111222', amount = 50, service_type = ['DirectPay', 'WeiXin', 'Alipay']\n\n    @allure.feature('Positive')\n    @allure.story('story')\n    @allure.step('step')\n    @pytest.mark.run(order=7)\n    # 可以用XPATH補一下應收帳款response的號碼\n    def test_deposit_card_success(username='jackson', pwd='a111222', amount=50, service_type=None):\n        # DirectPay(卡對卡), WeiXin(微信轉卡), Alipay(支付寶轉卡)\n    \n        count = 0\n        error = 0\n    \n        b.login(username, pwd)\n        if service_type is None:\n            service_type = ['DirectPay', 'WeiXin', 'Alipay']\n    \n        for typ in service_type:\n            cards = b.deposit(amount, typ)\n            if '123456789' in cards['text']:\n                lis = [\n                    cards['status_code'] == 200,\n                    '50' in cards['text'],\n                    '123456789' in cards['text']\n                       ]\n    \n                for judge in lis:\n                    count += 1\n                    if not judge:\n                        error += 1\n                        logging.debug('\\tlis的第%s行錯誤' % count)\n    \n                if error >= 1:\n                    raise AssertionError(\n                        \"\\tError count : %s\\n%s\" % (error, time.strftime('%Y-%m-%d %H:%M:%S')))\n            else:\n>               raise ValueError(\"Receivable's account incorrect with 123456789\")\nE               ValueError: Receivable's account incorrect with 123456789\n\ndeposit_test.py:97: ValueError",
    "steps" : [ {
      "name" : "step",
      "time" : {
        "start" : 1593598011530,
        "stop" : 1593598014102,
        "duration" : 2572
      },
      "status" : "broken",
      "statusMessage" : "ValueError: Receivable's account incorrect with 123456789\n",
      "statusTrace" : "  File \"c:\\users\\welly.chiang\\venv\\owmtest\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\welly.chiang\\PycharmProjects\\Owmtest\\baoApi\\deposit_test.py\", line 97, in test_deposit_card_success\n    raise ValueError(\"Receivable's account incorrect with 123456789\")\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'jackson'"
      }, {
        "name" : "pwd",
        "value" : "'a111222'"
      }, {
        "name" : "amount",
        "value" : "50"
      }, {
        "name" : "service_type",
        "value" : "None"
      } ],
      "shouldDisplayMessage" : true,
      "attachmentsCount" : 0,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "8d205c140499cb6e",
      "name" : "log",
      "source" : "8d205c140499cb6e.txt",
      "type" : "text/plain",
      "size" : 7482
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1,
    "stepsCount" : 1,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Positive"
  }, {
    "name" : "story",
    "value" : "story"
  }, {
    "name" : "tag",
    "value" : "run(order=7)"
  }, {
    "name" : "suite",
    "value" : "deposit_test"
  }, {
    "name" : "host",
    "value" : "CC-1902009"
  }, {
    "name" : "thread",
    "value" : "87764-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "deposit_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=7)" ]
  },
  "source" : "31e308fd6338358a.json",
  "parameterValues" : [ ]
}